### ISSUE TITLE
경고 메시지

### ISSUE THREAD

**Issue by Murianwind** [dugurs/kwh_to_won#11]
이전 업데이트 이후에도 아래와 같은 메시지가 추가로 출력됩니다.

-----

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 14:53:25 (4 occurrences)
Last logged: 14:53:27

DEVICE_CLASS_ENERGY was used from kwh_to_won, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please report it to the author of the 'kwh_to_won' custom integration
ENERGY_KILO_WATT_HOUR was used from kwh_to_won, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'kwh_to_won' custom integration

**Comment by dugurs** [comment]
빠진 부분이 있었네요. 수정하였습니다.
감사합니다.

**Comment by Murianwind** [comment]
감사합니다. ^^

-----
Murian Song

SW Testing Evangelist & Consultant / TOC Evangelist & Consultant

Blog: http://murianwind.blogspot.com

Twitter: http://twitter.com/murianwind

Facebook: http://www.facebook.com/murianwind


2024년 3월 5일 (화) 14:16, dugurs ***@***.***>님이 작성:
