### ISSUE TITLE
HA Core 2024.5.1 에서 재부팅을 하면 센서가 자동으로 로딩이 되지 않습니다.

### ISSUE THREAD

**Issue by Murianwind** [dugurs/kwh_to_won#12]
로거: homeassistant.helpers.frame
소스: helpers/frame.py:190
처음 발생: 09:22:31 (903 발생)
마지막 로그인: 16:10:56

Detected that custom integration 'kwh_to_won' calls async_create_task from a thread at custom_components/kwh_to_won/sensor.py, line 266: self.async_schedule_update_ha_state(True), please report it to the author of the 'kwh_to_won' custom integration

꼭 다시 불러오기를 해야 센서가 로딩이 되네요..

**Comment by dugurs** [comment]
수정하였습니다. 센서 로딩도 잘 되는 것 같습니다.

**Comment by Murianwind** [comment]
감사합니다. ^^
