### ISSUE TITLE
HA 5.0 업데이트 후 컴포넌트가 실행되지 않습니다.

### ISSUE THREAD

**Issue by Murianwind** [dugurs/kwh_to_won#5]
Logger: homeassistant.setup
Source: setup.py:214
First occurred: 06:20:53 (3 occurrences)
Last logged: 06:20:53

Setup failed for custom integration kwh_to_won: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)

이런 오류 로그가 출력되고 컴포넌트가 실행되지 않습니다.

**Comment by dugurs** [comment]
수정하였습니다.
감사합니다

**Comment by Murianwind** [comment]
> 수정하였습니다. 감사합니다

감사합니다. 즐거운 하루 보내세요. ^^
