### ISSUE TITLE
센서 __init__ 에서 forecast_energy_entity 사용문제

### ISSUE THREAD

**Issue by oukene** [dugurs/kwh_to_won#6]
self._forecast_energy_entity = forecast_energy_entity if (forecast_energy_entity !="") and _is_valid_state(self.hass.states.get(forecast_energy_entity)) else None

에서 HA 재시작시에 전기요금 컴포넌트와 외부 엔티티간에 로딩 순서에 따라 적용이 안되는 경우가 발생합니다.

전기요금 컴포넌트가 나중에 로드 된다면 상관없는데 먼저 로드 되면 적용이 되지 않습니다

**Comment by dugurs** [comment]
그럴 수 있겠네요.
상태 체크를 빼도록 하겠습니다.
감사합니다.

**Comment by oukene** [comment]
> 그럴 수 있겠네요. 상태 체크를 빼도록 하겠습니다. 감사합니다.

감사합니다~~
