### ISSUE TITLE
HA 경고 메시지

### ISSUE THREAD

**Issue by Murianwind** [dugurs/kwh_to_won#8]
HA Core 2025.01에 예정된 변경사항에 대한 경고메시지에 대해 업데이트 해주시면 감사하겠습니다.

Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 08:10:44 (28 occurrences)
Last logged: 08:11:24

DEVICE_CLASS_ENERGY was used from kwh_to_won, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please report it to the author of the 'kwh_to_won' custom integration
ENERGY_KILO_WATT_HOUR was used from kwh_to_won, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'kwh_to_won' custom integration
DEVICE_CLASS_MONETARY was used from kwh_to_won, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.MONETARY instead, please report it to the author of the 'kwh_to_won' custom integration

**Comment by dugurs** [comment]
내용 적용하여 업데이트 하였습니다.
제보 감사드립니다.

**Comment by Murianwind** [comment]
감사합니다.

새해 복 많이 많이 받으세요!!! ^^

-----
Murian Song

SW Testing Evangelist & Consultant / TOC Evangelist & Consultant

Blog: http://murianwind.blogspot.com

Twitter: http://twitter.com/murianwind

Facebook: http://www.facebook.com/murianwind


2024년 1월 5일 (금) 오후 1:01, dugurs ***@***.***>님이 작성:
